# Generated by Django 3.1.3 on 2021-06-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=900)),
                ('option1', models.CharField(max_length=800)),
                ('option2', models.CharField(max_length=800)),
                ('option3', models.CharField(max_length=800)),
                ('option4', models.CharField(max_length=800)),
                ('answer', models.CharField(max_length=800)),
                ('category', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='quiz_response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('q_id', models.CharField(max_length=900)),
                ('sub_answer', models.CharField(max_length=800)),
                ('corr_answer', models.CharField(max_length=800)),
                ('marks', models.CharField(max_length=800)),
                ('category', models.CharField(max_length=400)),
            ],
        ),
    ]
